### ISSUE TITLE
TypeError: Cannot read property 'filter' of null

### ISSUE THREAD

**Issue by ghost** [daleeidd/postcss-define-property#1]
First time trying to use postcss-define-property, getting [this error](https://github.com/daleeidd/postcss-define-property/files/41984/errorlog.txt) when I run the gulp task, even if I isolate the plugin. Still a bit new to postcss so I don't know if I've done something wrong.

**Comment by magenta404** [comment]
Can you please provide your code? I will need the CSS being parsed and the PostCSS related JS.

**Comment by ghost** [comment]
[Here you go](http://udy.io/rsc/archives/project.zip). I stripped it down to just my css. Same error is being thrown.
Just a heads up, I'm currently at school in web development so bear with me, a year ago you could have told me CSS was a type of spaghetti sauce and I wouldn't have known any better. The issue may very well be on my end.
I've also only been getting familiar with PostCSS for two days but, to be honest, your plugin is the one I'm most interested in using, I really want to get it working.
(sorry for the overly complicated CSS file structure)

**Comment by magenta404** [comment]
Thanks. There was a bug in the plugin's code. I will push a fix out soon.
